name: SemiModule
main: kr.eme.semiModule.SemiModule
version: 1.0
api-version: 1.20
depend:
  - SemiTradeShop
libraries:
  - com.github.shynixn.structureblocklib:structureblocklib-bukkit-api:2.13.0
  - com.github.shynixn.structureblocklib:structureblocklib-bukkit-core:2.13.0
commands:
  module:
    usage: /module or /모듈
    aliases: 모듈